//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ProjektKatastrophenschutz.ColorThemes;

namespace ProjektKatastrophenschutz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastServerAddress {
            get {
                return ((string)(this["LastServerAddress"]));
            }
            set {
                this["LastServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUserName {
            get {
                return ((string)(this["LastUserName"]));
            }
            set {
                this["LastUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ProjektKatastrophenschutz.ColorThemes.ColorTheme SelectedColorTheme {
            get
            {
                var currentTheme = (global::ProjektKatastrophenschutz.ColorThemes.ColorTheme)(this["SelectedColorTheme"]);
                if (currentTheme != null)
                    return currentTheme;

                return ColorTheme.DeepSea();
            }
            set {
                this["SelectedColorTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSaveSuccessMessageBoxes {
            get {
                return ((bool)(this["ShowSaveSuccessMessageBoxes"]));
            }
            set {
                this["ShowSaveSuccessMessageBoxes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowJobsViewFilters
        {
            get
            {
                return (bool) (this["ShowJobsViewFilters"]);
            }
            set
            {
                this["ShowJobsViewFilters"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowForcesViewFilters
        {
            get
            {
                return (bool)(this["ShowForcesViewFilters"]);
            }
            set
            {
                this["ShowForcesViewFilters"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticallySetJobInProgressAfterForceAssignment
        {
            get
            {
                return (bool)(this["AutomaticallySetJobInProgressAfterForceAssignment"]);
            }
            set
            {
                this["AutomaticallySetJobInProgressAfterForceAssignment"] = value;
            }
        }
    }
}
